apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Release.Namespace }}
data:
  Caddyfile: |
    :80 {
          root * /var/www/html
          file_server
    }